default:
  image: python
  tags: [asprunner]

variables:
  GIT_DEPTH: 0

# build_example:
#   stage: build
#   script:
#     - pip install copier
#     - copier copy --trust -d "project_name=Sample Project" --defaults . ./example
#   artifacts:
#     paths:
#       - example
#   only:
#     - main

# publish_example:
#   stage: build
#   script:
#     - cd example
#     - git init
#     - git remote add origin git@git01.iis.fhg.de:mkj/sample-project.git
#     - make example-setup
#   only:
#     - main

before_script:
  # creating example projects using copier requires a git identity
  - git config --global user.name "ci-runner"
  - git config --global user.email "ci-runner@gitlab.cc-asp.fraunhofer.de"

dist:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - build/

docs:
  stage: build
  script:
    - apt-get update && apt-get install tree
    - pip install .[doc]
    - make docs
  artifacts:
    paths:
      - build/docs

pages:
  script:
    - mv build/docs public
  needs:
    - docs
  artifacts:
    paths:
      - public
  only:
    - main
